name: todo_with_hive_db
description: Flutter Todo App with HiveDB for data storing

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.3
  intl: ^0.17.0

  build_runner: ^2.0.6
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  build_runner: ^2.1.4
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
